-- delete the schema users if already existing by:

DROP USER FPOS_Schema CASCADE;
DROP USER ROS_Schema CASCADE;

-- allow the user additional priv to support cpe shared database connection 
GRANT CREATE USER TO {DB_NAME};
GRANT ALTER ANY SEQUENCE TO {DB_NAME};
GRANT ALTER ANY TABLE TO {DB_NAME};
GRANT ANALYZE ANY TO {DB_NAME};
GRANT CREATE ANY INDEX TO {DB_NAME};
GRANT CREATE ANY SEQUENCE TO {DB_NAME};
GRANT CREATE ANY TABLE TO {DB_NAME};
GRANT CREATE ANY VIEW TO {DB_NAME};
GRANT DELETE ANY TABLE TO {DB_NAME};
GRANT DROP ANY INDEX TO {DB_NAME};
GRANT DROP ANY SEQUENCE TO {DB_NAME};
GRANT DROP ANY TABLE TO {DB_NAME};
GRANT DROP ANY VIEW TO {DB_NAME};
GRANT INSERT ANY TABLE TO {DB_NAME};
GRANT LOCK ANY TABLE TO {DB_NAME};
GRANT SELECT ANY SEQUENCE TO {DB_NAME};
GRANT SELECT ANY TABLE TO {DB_NAME};
GRANT SELECT ON ALL_USERS TO {DB_NAME};
GRANT UPDATE ANY TABLE TO {DB_NAME};
grant  CREATE TABLE to {DB_NAME};
grant  CREATE PROCEDURE to {DB_NAME};
grant  CREATE SEQUENCE to {DB_NAME};
grant  CREATE VIEW to {DB_NAME};
grant execute on dbms_system to {DB_NAME}; 
grant connect to {DB_NAME};
ALTER USER {DB_NAME} default tablespace {DB_NAME}DATATS QUOTA UNLIMITED ON {DB_NAME}DATATS;

EXIT;
