#Script by default has all the default db names generated by the scripts
# -- update this list before you run clean DB option if you have different DB names

./forceDropDB.sh ADPBASE;
./forceDropDB.sh PROJ1;
./forceDropDB.sh PROJ2;
./forceDropDB.sh PROJ3;
./forceDropDB.sh PROJ4;
./forceDropDB.sh DEVOS1;
./forceDropDB.sh APPDB;
./forceDropDB.sh AAEDB;
./forceDropDB.sh GCDDB;
./forceDropDB.sh AEOS;
./forceDropDB.sh BASDB;
./forceDropDB.sh ICNDB;