-- Creating DB named: ANSIICN

CREATE DATABASE ANSIICN AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;
CONNECT TO ANSIICN;
GRANT DBADM ON DATABASE TO USER fncmuser;
CONNECT RESET;
