-- Creating DB named: ANSIOS1
CREATE DATABASE ANSIOS1 AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;

CONNECT TO ANSIOS1;

-- Create bufferpool
CREATE BUFFERPOOL ANSIOS1_1_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL ANSIOS1_2_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL ANSIOS1_3_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;

-- Create table spaces
CREATE LARGE TABLESPACE OSDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL ANSIOS1_1_32K;
CREATE LARGE TABLESPACE VWDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL ANSIOS1_2_32K;
CREATE USER TEMPORARY TABLESPACE ANSIOS1_TMP_TBS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL ANSIOS1_3_32K;

-- Grant permissions to DB user
GRANT CREATETAB,CONNECT ON DATABASE TO USER fncmuser;
GRANT USE OF TABLESPACE OSDATA_TS TO USER fncmuser;
GRANT USE OF TABLESPACE VWDATA_TS TO USER fncmuser;
GRANT USE OF TABLESPACE ANSIOS1_TMP_TBS TO USER fncmuser;
GRANT SELECT ON SYSIBM.SYSVERSIONS TO USER fncmuser;
GRANT SELECT ON SYSCAT.DATATYPES TO USER fncmuser;
GRANT SELECT ON SYSCAT.INDEXES TO USER fncmuser;
GRANT SELECT ON SYSIBM.SYSDUMMY1 TO USER fncmuser;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO USER fncmuser;
GRANT IMPLICIT_SCHEMA ON DATABASE TO USER fncmuser;


-- Apply DB tunings
UPDATE DB CFG FOR ANSIOS1 USING LOCKTIMEOUT 30;
UPDATE DB CFG FOR ANSIOS1 USING LOGFILSIZ 6000; 

-- Notes: Please verify below environment configuration settings were applied to the Db2 server.
-- db2set DB2_WORKLOAD=FILENET_CM
-- db2set DB2_MINIMIZE_LISTPREFETCH=YES

CONNECT RESET;

-- Done creating and tuning DB named: ANSIOS1
