-- Creating DB named: ANSIGCD 
CREATE DATABASE ANSIGCD AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;

CONNECT TO ANSIGCD;

-- Create bufferpool 
CREATE BUFFERPOOL ANSIGCD_1_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL ANSIGCD_2_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;

-- Create table spaces
CREATE REGULAR TABLESPACE GCDDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL ANSIGCD_1_32K;

CREATE USER TEMPORARY TABLESPACE ANSIGCD_TMP_TBS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL ANSIGCD_2_32K;

-- Grant permissions to DB user
GRANT CREATETAB,CONNECT ON DATABASE TO user fncmuser;
GRANT USE OF TABLESPACE GCDDATA_TS TO user fncmuser;
GRANT USE OF TABLESPACE ANSIGCD_TMP_TBS TO user fncmuser;
GRANT SELECT ON SYSIBM.SYSVERSIONS to user fncmuser;
GRANT SELECT ON SYSCAT.DATATYPES to user fncmuser;
GRANT SELECT ON SYSCAT.INDEXES to user fncmuser;
GRANT SELECT ON SYSIBM.SYSDUMMY1 to user fncmuser;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD to user fncmuser;
GRANT IMPLICIT_SCHEMA ON DATABASE to user fncmuser;

-- Apply DB tunings
UPDATE DB CFG FOR ANSIGCD USING LOCKTIMEOUT 30;
UPDATE DB CFG FOR ANSIGCD USING APPLHEAPSZ 2560;

CONNECT RESET;

-- Notes: After DB be created, please set below setting.
-- db2set DB2_WORKLOAD=FILENET_CM
-- db2set DB2_MINIMIZE_LISTPREFETCH=YES

-- Done creating and tuning DB named: ANSIGCD
