- name: "Make create_secret.sh executable"
  file:
    dest: /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/create_secret.sh
    mode: a+x

- name: "Make ibm-cp4ba-db-ssl-cert-secret-for-sql.sh executable"
  file:
    dest: /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/cp4ba_db_ssl_secret/sql/ibm-cp4ba-db-ssl-cert-secret-for-sql.sh
    mode: a+x

- name: "Make ibm-cp4ba-ldap-ssl-cert-secret.sh executable"
  file:
    dest: /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/cp4ba_ldap_ssl_secret/ibm-cp4ba-ldap-ssl-cert-secret.sh
    mode: a+x

- name: "Update create_secrets.sh base directory path"
  ansible.builtin.command: sed -i -E 's|[^,]*cert-kubernetes|kubectl apply -f "/opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes|g' /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/create_secret.sh

- name: "Strip db-ssl-cert secret comment in script"
  ansible.builtin.command: sed -i -E 's|[^,]*ibm-cp4ba-db-ssl-cert-secret-for-sql.sh["]||g' /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/create_secret.sh

- name: "Update create_secrets.sh db-ssl-cert secret script path"
  ansible.builtin.command: sed -i -E 's|[^,]*ibm-cp4ba-db-ssl-cert-secret-for-sql.sh|/opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/cp4ba_db_ssl_secret/sql/ibm-cp4ba-db-ssl-cert-secret-for-sql.sh|g' /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/create_secret.sh

- name: "Strip ldap-ssl-cert secret comment in script"
  ansible.builtin.command: sed -i -E 's|[^,]*ibm-cp4ba-ldap-ssl-cert-secret.sh["]||g' /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/create_secret.sh

- name: "Update create_secrets.sh ldap-ssl-cert secret script path"
  ansible.builtin.command: sed -i -E 's|[^,]*ibm-cp4ba-ldap-ssl-cert-secret.sh|/opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/cp4ba_ldap_ssl_secret/ibm-cp4ba-ldap-ssl-cert-secret.sh|g' /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/create_secret.sh

- name: "Run 'create_secret.sh' script to create ADP secrets"
  ansible.builtin.shell:
    ./create_secret.sh
  args:
    chdir: /opt/{{ adpVars.deploymentNamespace }}/cert-kubernetes/scripts/cp4ba-prerequisites/

- name: "Create 'github-cert' secret"
  ansible.builtin.command: kubectl create secret generic github-cert --from-file=tls.crt="./certs/github/github.pem" -n "{{ adpVars.deploymentNamespace }}"

