-- Creating DB named: GCD_DB2 
CREATE DATABASE GCD_DB2 AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;

CONNECT TO GCD_DB2;

-- Create bufferpool 
CREATE BUFFERPOOL GCD_DB2_1_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL GCD_DB2_2_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;

-- Create table spaces
CREATE REGULAR TABLESPACE GCDDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL GCD_DB2_1_32K;

CREATE USER TEMPORARY TABLESPACE GCD_DB2_TMP_TBS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL GCD_DB2_2_32K;

-- Grant permissions to DB user
GRANT CREATETAB,CONNECT ON DATABASE TO user db2inst1;
GRANT USE OF TABLESPACE GCDDATA_TS TO user db2inst1;
GRANT USE OF TABLESPACE GCD_DB2_TMP_TBS TO user db2inst1;
GRANT SELECT ON SYSIBM.SYSVERSIONS to user db2inst1;
GRANT SELECT ON SYSCAT.DATATYPES to user db2inst1;
GRANT SELECT ON SYSCAT.INDEXES to user db2inst1;
GRANT SELECT ON SYSIBM.SYSDUMMY1 to user db2inst1;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD to user db2inst1;
GRANT IMPLICIT_SCHEMA ON DATABASE to user db2inst1;
CREATE SCHEMA db2inst1 AUTHORIZATION db2inst1;

-- Apply DB tunings
UPDATE DB CFG FOR GCD_DB2 USING LOCKTIMEOUT 30;
UPDATE DB CFG FOR GCD_DB2 USING APPLHEAPSZ 2560;

CONNECT RESET;

-- Notes: After DB be created, please set below setting.
-- db2set DB2_WORKLOAD=FILENET_CM
-- db2set DB2_MINIMIZE_LISTPREFETCH=YES

-- Done creating and tuning DB named: GCD_DB2
