-- Creating DB named: OS1_DB2
CREATE DATABASE OS1_DB2 AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;

CONNECT TO OS1_DB2;

-- Create bufferpool
CREATE BUFFERPOOL OS1_DB2_1_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL OS1_DB2_2_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL OS1_DB2_3_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;

-- Create table spaces
CREATE LARGE TABLESPACE OSDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL OS1_DB2_1_32K;
CREATE LARGE TABLESPACE VWDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL OS1_DB2_2_32K;
CREATE USER TEMPORARY TABLESPACE OS1_DB2_TMP_TBS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL OS1_DB2_3_32K;

-- Grant permissions to DB user
GRANT CREATETAB,CONNECT ON DATABASE TO USER db2inst1;
GRANT USE OF TABLESPACE OSDATA_TS TO USER db2inst1;
GRANT USE OF TABLESPACE VWDATA_TS TO USER db2inst1;
GRANT USE OF TABLESPACE OS1_DB2_TMP_TBS TO USER db2inst1;
GRANT SELECT ON SYSIBM.SYSVERSIONS TO USER db2inst1;
GRANT SELECT ON SYSCAT.DATATYPES TO USER db2inst1;
GRANT SELECT ON SYSCAT.INDEXES TO USER db2inst1;
GRANT SELECT ON SYSIBM.SYSDUMMY1 TO USER db2inst1;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO USER db2inst1;
GRANT IMPLICIT_SCHEMA ON DATABASE TO USER db2inst1;
CREATE SCHEMA db2inst1 AUTHORIZATION db2inst1;

-- Apply DB tunings
UPDATE DB CFG FOR OS1_DB2 USING LOCKTIMEOUT 30;
UPDATE DB CFG FOR OS1_DB2 USING LOGFILSIZ 6000; 

-- Notes: Please verify below environment configuration settings were applied to the Db2 server.
-- db2set DB2_WORKLOAD=FILENET_CM
-- db2set DB2_MINIMIZE_LISTPREFETCH=YES

CONNECT RESET;

-- Done creating and tuning DB named: OS1_DB2
