# YAML template for ibm-fncm-secret secret
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: ibm-fncm-secret
  # DO NOT change the content of metadata.labels
  labels:
    gcd-db-server: sql
    db-name: ibm-fncm-secret
stringData:
  appLoginUsername: "group0001usr0001"
  appLoginPassword: "passw0rd"
  gcdDBUsername: "cpeadmin"
  gcdDBPassword: "Password1"
  os1DBUsername: "cpeadmin"
  os1DBPassword: "Password1"
  ltpaPassword: "changeit"
  keystorePassword: "changeit"
